---
### Cinder API

- include: bigip_complex.yaml
  vars:
    pool_name: cinder_api
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['cinder_api']}}"
    pool_member_port: 8776
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "cinder-api"
    vs_name: "cinder-api"
    vs_port: 8776
#    vs_snat: "{{ snat_pool }}" 
    snat_pool: "SNAT_Private"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - cinder
## Glance API

- include: bigip_complex.yaml
  vars:
    pool_name: glance_api
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['glance_api']}}"
    pool_member_port: 9292
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "glance-api"
    vs_name: "glance-api"
    snat_pool: "SNAT_Private"
    vs_port: 9292
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - glance
## Glance REGISTRY

- include: bigip_complex.yaml
  vars:
    pool_name: glance_registry
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['glance_api']}}"
    pool_member_port: 9191
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "glance-registry"
    vs_name: "glance-registry"
    snat_pool: "SNAT_Private"
    vs_port: 9191
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - glance

### Heat API

- include: bigip_complex.yaml
  vars:
    pool_name: heat_api
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['heat_api']}}"
    pool_member_port: 8004
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "heat-api"
    vs_name: "heat-api"
    vs_port: 8004
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - heat

### Galera
### iRule should be created manually to support active/standby servers

#- include: bigip_complex.yaml
#  vars:
#    pool_name: galera_all
#    pool_lb_method: "round_robin"
#    pool_monitors:
#        - tcp
#    inv_hosts_group: "{{ groups['galera_all']}}"
#    pool_member_port: 3306
#    vs_profiles1:
#        - tcp
#    vs_address: 
#        - "{{ internal_vip }}"
#        - "{{ external_vip }}"
#    vs_description: "galera"
#    vs_name: "galera"
#    vs_port: 3306
#    snat_pool: "SNAT_Public"
##    vs_snat1: "Automap"
#    va_address: "{{ vs_address }}"
##    monitor_name: "glance_http"
##    send_string: "GET "
##    receive_string: ""
#  tags:
#    - galera

### Horizon

- include: bigip_complex.yaml
  vars:
    pool_name: horizon_all
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['horizon_all']}}"
    pool_member_port: 80
    pub_profiles:
        - http
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    vs_description: "horizon"
    vs_name: "horizon"
    vs_port: 80
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - horizon

### Horizon SSL

- include: bigip_complex.yaml
  vars:
    pool_name: horizon_ssl_all
    pool_monitors:
        - tcp
    inv_hosts_group: "{{ groups['horizon_all']}}"
    pool_member_port: 443
    pub_profiles:
        - http
        - Openstack_SSL
        - F5-self
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    vs_description: "horizon-ssl"
    vs_name: "horizon-ssl"
    vs_port: 443
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - horizon

### Keystone pub

- include: bigip_complex.yaml
  vars:
    pool_name: keystone-pub
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['keystone_all']}}"
    pool_member_port: 5000
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "keystone-pub"
    vs_name: "keystone-pub"
    vs_port: 5000
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - keystone

### Keystone admin

- include: bigip_complex.yaml
  vars:
    pool_name: keystone-admin
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['keystone_all']}}"
    pool_member_port: 35357
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "keystone-admin"
    vs_name: "keystone-admin"
    vs_port: 35357
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - keystone

### Neutron server

- include: bigip_complex.yaml
  vars:
    pool_name: neutron
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['neutron_server']}}"
    pool_member_port: 9696
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "neutron"
    vs_name: "neutron"
    vs_port: 9696
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - neutron

### Nova API

- include: bigip_complex.yaml
  vars:
    pool_name: nova-api
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['nova_api_os_compute']}}"
    pool_member_port: 8774
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "nova-api"
    vs_name: "nova-api"
    vs_port: 8774
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - nova

### Nova API Metadata

- include: bigip_complex.yaml
  vars:
    pool_name: nova-api-metadata
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['nova_api_metadata']}}"
    pool_member_port: 8775
    pub_profiles:
        - http
        - Openstack_SSL
    priv_profiles:
        - http
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "nova-api-metadata"
    vs_name: "nova-api-metadata"
    vs_port: 8775
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - nova

### Nova Console NoVNC

- include: bigip_complex.yaml
  vars:
    pool_name: nova-console
    pool_monitors:
        - tcp
    inv_hosts_group: "{{ groups['nova_console']}}"
    pool_member_port: 6082
    pub_profiles:
        - tcp
    priv_profiles:
        - tcp
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "nova-console"
    vs_name: "nova-console"
    vs_port: 6082
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - nova

### Repo

- include: bigip_complex.yaml
  vars:
    pool_name: repo
    pool_monitors:
        - http
    inv_hosts_group: "{{ groups['pkg_repo']}}"
    pool_member_port: 8181
    pub_profiles:
        - http
    priv_profiles:
        - http
    pub_address:
        - "{{ external_vip }}"
    priv_address:
        - "{{ internal_vip }}"
    vs_description: "repo"
    vs_name: "repo"
    vs_port: 8181
    snat_pool: "SNAT_Private"
#    vs_snat1: "Automap"
    va_address: "{{ vs_address }}"
#    monitor_name: "glance_http"
#    send_string: "GET "
#    receive_string: ""
  tags:
    - repo
